import { Suspense } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { 
  Calendar, 
  Clock, 
  TrendingUp, 
  Star, 
  Trophy, 
  Users, 
  Award, 
  Activity,
  BarChart3,
  Coins,
  Gift,
  Heart,
  Flame,
  Lightning,
  Zap,
  Target,
  Crown,
  Medal,
  Shield,
  Gamepad2,
  Share2
} from "lucide-react"
import DailyRecapDisplay from "@/components/shared/daily-recap-display"
import { createClient } from "@supabase/supabase-js"

// Server-side function to get the most recent daily recap
async function getDailyRecap() {
  try {
    console.log("🔍 [Server] Fetching most recent daily recap from database...")

    // Use service role key for server-side access
    const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!)

    // Get the most recent recap
    const { data, error } = await supabase
      .from("daily_recaps")
      .select("id, date, recap_data, created_at, updated_at")
      .order("updated_at", { ascending: false })
      .limit(1)

    if (error) {
      console.error("❌ [Server] Database error:", error)
      return null
    }

    if (!data || data.length === 0) {
      console.log("📭 [Server] No saved recap found in database")
      return null
    }

    const recap = data[0]
    console.log("✅ [Server] Found saved recap:", {
      id: recap.id,
      date: recap.date,
      updated_at: recap.updated_at,
      hasRecapData: !!recap.recap_data,
      teamCount: recap.recap_data?.team_recaps?.length || 0,
      timeWindow: recap.recap_data?.time_window_hours || "unknown",
      totalMatches: recap.recap_data?.total_matches || 0,
    })

    // Validate recap data structure
    if (!recap.recap_data || !recap.recap_data.team_recaps) {
      console.error("❌ [Server] Invalid recap data structure:", recap.recap_data)
      return null
    }

    // Ensure time window is set
    if (!recap.recap_data.time_window_hours) {
      console.warn("⚠️ [Server] Setting default time window to 24 hours")
      recap.recap_data.time_window_hours = 24
    }

    console.log("✅ [Server] Returning valid recap data with", recap.recap_data.team_recaps.length, "teams")
    return recap.recap_data
  } catch (error) {
    console.error("❌ [Server] Error fetching daily recap:", error)
    return null
  }
}

function LoadingSkeleton() {
  return (
    <div className="space-y-6">
      <Card>
        <CardContent className="p-6">
          <Skeleton className="h-8 w-64 mb-2" />
          <Skeleton className="h-4 w-96 mb-4" />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Skeleton className="h-24 w-full" />
            <Skeleton className="h-24 w-full" />
          </div>
        </CardContent>
      </Card>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {[1, 2, 3, 4].map((i) => (
          <Card key={i}>
            <CardContent className="p-6">
              <Skeleton className="h-6 w-32 mb-2" />
              <Skeleton className="h-4 w-48 mb-4" />
              <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}

async function DailyRecapContent() {
  const recapData = await getDailyRecap()

  if (!recapData) {
    return (
      <Card>
        <CardContent className="text-center py-8">
          <p className="text-muted-foreground mb-2">No daily recap available yet.</p>
          <p className="text-sm text-muted-foreground">
            Daily recaps are generated by administrators and will appear here once available.
          </p>
          <div className="mt-4 p-4 bg-blue-50 dark:bg-blue-950/20 rounded-lg">
            <p className="text-xs text-blue-600 dark:text-blue-400">
              <strong>For Admins:</strong> Generate a recap from the admin panel (/admin → Daily Recap) to see it here.
            </p>
          </div>
        </CardContent>
      </Card>
    )
  }

  return <DailyRecapDisplay recapData={recapData} showFullRoster={true} />
}

export default function DailyRecapPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-hockey-ice/5 to-hockey-ice/10">
      {/* Hero Section */}
      <div className="relative overflow-hidden bg-gradient-to-br from-hockey-green/20 via-hockey-blue/20 to-hockey-green/20 border-b border-hockey-green/20">
        <div className="absolute inset-0 bg-gradient-to-r from-hockey-green/5 to-transparent" />
        <div className="absolute top-0 right-0 w-32 h-32 bg-hockey-green/10 rounded-full -translate-y-16 translate-x-16" />
        <div className="absolute bottom-0 left-0 w-24 h-24 bg-hockey-blue/10 rounded-full translate-y-12 -translate-x-12" />
        
        <div className="relative container mx-auto px-4 py-16">
          <div 
            className="text-center"
          >
            <div className="inline-flex items-center gap-3 mb-6">
              <div className="p-3 bg-gradient-to-r from-hockey-green to-hockey-blue rounded-xl">
                <Calendar className="h-8 w-8 text-white" />
              </div>
              <h1 className="text-5xl font-bold hockey-gradient-text">Daily Recap</h1>
            </div>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
              Stay updated with the latest highlights, statistics, and stories from the Secret Chel Society. 
              Your daily dose of SCS action and insights.
            </p>
            <div className="h-1 w-32 bg-gradient-to-r from-hockey-green to-transparent rounded-full mx-auto" />
          </motion.div>
        </div>
      </div>

      {/* Main Content */}
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
            <div>
              <h2 className="text-3xl font-bold mb-2">Today's Highlights</h2>
              <p className="text-muted-foreground">Comprehensive AI-powered analysis of recent matches and team performances</p>
            </div>
            <div className="flex gap-2">
              <Button className="btn-ice" variant="outline">
                <Calendar className="h-4 w-4 mr-2" />
                View Archive
              </Button>
              <Button className="btn-championship">
                <Share2 className="h-4 w-4 mr-2" />
                Share Recap
              </Button>
            </div>
          </div>
        </motion.div>

        <Suspense fallback={<LoadingSkeleton />}>
          <DailyRecapContent />
        </Suspense>
      </div>
    </div>
  )
}

// Force dynamic rendering to ensure fresh data
export const dynamic = "force-dynamic"
export const revalidate = 0
