// Generated by https://supabase.com/docs/reference/javascript/generating-types

type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

type UserRole = 'admin' | 'user' | 'moderator'
type ConsoleType = 'ps5' | 'xbox' | 'pc'
type Position = 'C' | 'LW' | 'RW' | 'LD' | 'RD' | 'G'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string | null
          gamer_tag_id: string | null
          discord_name: string | null
          primary_position: Position | null
          secondary_position: Position | null
          console: ConsoleType | null
          avatar_url: string | null
          role: UserRole
          created_at: string
          updated_at: string
          last_login: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          email?: string | null
          gamer_tag_id?: string | null
          discord_name?: string | null
          primary_position?: Position | null
          secondary_position?: Position | null
          console?: ConsoleType | null
          avatar_url?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
          last_login?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          email?: string | null
          gamer_tag_id?: string | null
          discord_name?: string | null
          primary_position?: Position | null
          secondary_position?: Position | null
          console?: ConsoleType | null
          avatar_url?: string | null
          role?: UserRole
          created_at?: string
          updated_at?: string
          last_login?: string | null
          is_active?: boolean
        }
      },
      player_bidding: {
        Row: {
          id: string
          player_id: string | null
          team_id: string | null
          bid_amount: number | null
          bid_expires_at: string | null
          status: string | null
          created_at: string | null
          updated_at: string | null
          processed: boolean | null
          won_bid: boolean | null
          processed_at: string | null
          cancellation_reason: string | null
          finalized: boolean | null
          user_id: string | null
        }
        Insert: {
          id?: string
          player_id?: string | null
          team_id?: string | null
          bid_amount?: number | null
          bid_expires_at?: string | null
          status?: string | null
          created_at?: string | null
          updated_at?: string | null
          processed?: boolean | null
          won_bid?: boolean | null
          processed_at?: string | null
          cancellation_reason?: string | null
          finalized?: boolean | null
          user_id?: string | null
        }
        Update: {
          id?: string
          player_id?: string | null
          team_id?: string | null
          bid_amount?: number | null
          bid_expires_at?: string | null
          status?: string | null
          created_at?: string | null
          updated_at?: string | null
          processed?: boolean | null
          won_bid?: boolean | null
          processed_at?: string | null
          cancellation_reason?: string | null
          finalized?: boolean | null
          user_id?: string | null
        }
      }
      // Add other tables as needed
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      process_bid_transaction: {
        Args: {
          p_winner_id: string
          p_winning_amount: number
          p_user_id: string
          p_bid_id: string
          p_player_id: string
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
